defmodule CoincheckEx.Currency do
  def jpy, do: "JPY"
  def btc, do: "BTC"
  def eth, do: "ETH"
  def etc, do: "ETC"
  def dao, do: "DAO"
  def lsk, do: "LSK"
  def fct, do: "FCT"
  def xmr, do: "XMR"
  def rep, do: "REP"
  def xrp, do: "XRP"
  def zec, do: "ZEC"
end

defmodule CoincheckEx.Currency.Pairs do
  def btc_jpy, do: "btc_jpy"
  def eth_jpy, do: "eth_jpy"
  def etc_jpy, do: "etc_jpy"
  def dao_jpy, do: "dao_jpy"
  def lsk_jpy, do: "lsk_jpy"
  def fct_jpy, do: "fct_jpy"
  def xmr_jpy, do: "xmr_jpy"
  def rep_jpy, do: "rep_jpy"
  def xrp_jpy, do: "xrp_jpy"
  def zec_jpy, do: "zec_jpy"
  def eth_btc, do: "eth_btc"
  def etc_btc, do: "etc_btc"
  def lsk_btc, do: "lsk_btc"
  def fct_btc, do: "fct_btc"
  def xmr_btc, do: "xmr_btc"
  def rep_btc, do: "rep_btc"
  def xrp_btc, do: "xrp_btc"
  def zec_btc, do: "zec_btc"
end
